[project]
name = "mkdocs-action-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.11",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=0.29.1",
]
